version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak
    ports:
      - "8090:8080"
volumes:
  keycloak_data:
    driver: local
